---
- hosts: arista
  connection: network_cli
  remote_user: admin
  become: yes
  become_method: enable
  vars:
    ansible_network_os: "eos"
  tasks:
    - eos_vlan:
        state: active
        purge: yes
        aggregate:
          - { vlan_id: 1, name: default }
          - { vlan_id: 2, name: Vl2 }
          - { vlan_id: 3, state: suspend }
          - { vlan_id: 4 }
          - { vlan_id: 5 }
          - { vlan_id: 6 }
          - { vlan_id: 7 }
          - { vlan_id: 8 }
          - { vlan_id: 9 }
          - { vlan_id: 10 }
